name: Deploy Vue App to GitHub Pages

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    # 构建 Job
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: |
                  corepack enable
                  pnpm install

            - name: Get contributor count for mc521-lab/wiki
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动提供的访问令牌
              run: |
                  $count = 0
                  $page = 1
                  while ($true) {
                      $url = "https://api.github.com/repos/mc521-lab/wiki/contributors?per_page=100&page=$page"
                      $headers = @{ Authorization = "token $env:GH_TOKEN" }
                      $result = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
                      $num = $result.Count
                      if ($num -eq 0) { break }
                      $count += $num
                      $page += 1
                  }
                  Write-Output "Total contributors: $count"
                  "`nCONTRIBUTOR_COUNT=$count" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

            - name: Set Environment Variables - Site Meta
              run: |
                  $files = Get-ChildItem -Recurse -File -Force | Where-Object { -not ($_.FullName -match '\\node_modules\\') }
                  $filesCount = $files.Count
                  "`nFILES_COUNT=$filesCount" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
                      
                  $vueFiles = Get-ChildItem -Recurse -Path "./src/views" -Include "*.vue" -File
                  $pagesCount = $vueFiles.Count
                  "`nPAGES_COUNT=$pagesCount" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

            - name: Build Dynamic Pages
              run: ./gen/mcw-builder.exe

            - name: Build Vue project
              env:
                  MCW_PAGES_COUNT: ${{ env.PAGES_COUNT }}
                  MCW_FILES_COUNT: ${{ env.FILES_COUNT }}
                  MCW_CONTRIBUTORS: ${{ env.CONTRIBUTOR_COUNT }}
              run: pnpm build

            - name: Upload build artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./dist

    # 部署 Job
    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
